### ISSUE TITLE
Interfisa cambio su modo de proveer cotizaciones

### ISSUE THREAD

**Issue by aVolpe** [melizeche/dolarPy#11]
Anteriormente la página de interfisa retornaba la cotización diaria, en algun momento dado, dejaron de retornar la cotización actualizada y siempre retorna la misma (5750 y 5830).

Ahora al cargar la página hace otro request, a la url `https://seguro.interfisa.com.py/rest/cotizaciones`, la cual retorna un JSON con los valores actualizados, y actualiza los valores con js.

**Comment by melizeche** [comment]
Fixed en #14 muchas gracias @aVolpe @luiscardozo

**Comment by melizeche** [comment]
Fixed en #14 muchas gracias @aVolpe @luiscardozo
