### ISSUE TITLE
Cards overlaps when resizing

### ISSUE THREAD

**Issue by melizeche** [melizeche/dolarPy#20]
Responsiveness issue, the "cards" overlaps in small screens

## Expected Behavior
No overlap when resizing ¯\_(ツ)_/¯

## Current Behavior
![dolarpy_rendering2](https://user-images.githubusercontent.com/484773/67012439-c96c8000-f0c7-11e9-8807-a1244af44fe0.gif)

**Comment by cos1715** [comment]
I can do this

**Comment by Shubham0812** [comment]
Okay , will look into this. Do you want the cards to wrap below one another?

**Comment by melizeche** [comment]
Fixed, and merged in #22 
Thanks you all!
