### ISSUE TITLE
Replace Alberdi from tweets

### ISSUE THREAD

**Issue by melizeche** [melizeche/dolarPy#30]
**Describe the bug**
Since a while Alberdi exchange rate website is not working, so the bot tweets 0 as the exchange rate

**Context**
* [ ] Website
* [ ] API
* [x] other
   This has to be done in `single_tweet_bot.py` file

**Expected behavior**
Replace Alberdi with other exchange

**Screenshots**

![image](https://user-images.githubusercontent.com/484773/96639995-e77f4880-12f8-11eb-8df5-0aa79ad7dd23.png)

**Comment by alcides29** [comment]
Podría ver este tema
