### ISSUE TITLE
Cambios Alberdi nueva url

### ISSUE THREAD

**Issue by mariodot** [melizeche/dolarPy#7]
Cambios Alberdi carga un archivo json desde la siguiente dirección

http://cambiosalberdi.com/ws/getCotizaciones.json

**Comment by melizeche** [comment]
Actualmente el el scraper consulta el webservice `ws://cambiosalberdi.com:9300` que ventajas tendría obtener la cotización desde el json?

**Comment by melizeche** [comment]
Solucionado por #9
